import themelist from './themelist.json';
import { adaptMonacoThemeToUI } from './themeAdapter';

const themeModules = import.meta.glob('./*.json');
const loadedThemes = new Map();

/**
 * Get a flat array of all available themes mapped from themelist.json
 */
export const getAvailableThemes = () => {
  return Object.entries(themelist).map(([id, label]) => ({
    id,
    label
  }));
};

/**
 * Dynamically load a theme JSON from the local generic theme files
 */

export const loadTheme = async (themeId) => {
  if (loadedThemes.has(themeId)) {
    return loadedThemes.get(themeId);
  }

  const label = themelist[themeId];
  if (!label) {
    throw new Error(`Theme ${themeId} not found in themelist.json`);
  }

  const path = `./${label}.json`;
  const importFn = themeModules[path];

  if (!importFn) {
    throw new Error(`Theme file ${path} not found in themes folder`);
  }

  // Execute the dynamic import generated by Vite
  const themeDataModule = await importFn();
  const themeData = themeDataModule.default || themeDataModule;

  // Infer and adapt generic UI colors from Monaco schema
  const uiColors = adaptMonacoThemeToUI(themeData);

  const result = {
    id: themeId,
    label,
    monacoThemeData: themeData,
    uiColors,
    isDark: themeData.base !== 'vs' // 'vs' is light, 'vs-dark' / 'hc-black' is dark
  };

  loadedThemes.set(themeId, result);
  return result;
};
